---
title: "tutorial_quarto"
format: html
---


Quarto es una herramienta que te permite generar documentos y reportes de manera muy sencilla utilizando bloques de código de R. En estos reportes puedes incluir tablas, gráficos, y mucho más, de forma atractiva, para poder compartir tus análisis y resultados con otras personas.


## Crear un reporte Quarto

En RStudio, crear un nuevo archivo desde _New File_, y elegir _Quarto Document_.

Render


## Markdown
https://quarto.org/docs/authoring/markdown-basics.html

- negrita, itálica
- líneas separadoras
- enlaces
- imágenes
- html


```markdown
**negrita**
*itálica* o _itálica_
<u>subrayado</u>
~~tachado~~
`código`
```

<div style = "line-height: 6pt;">

**negrita**

*itálica*	o _itálica_

<u>subrayado</u>

~~tachado~~

`código`

</div>

### Separadores

```
----
```

### Enlaces
```
[Texto](http://enlace.cl)
```

### Notas al pie
Agregar una nota al pie[^1]. También se puede agregar directamente en el texto^[De esta forma]. 



```markdown
Agregar una nota al pie[^1].
[^1]: Esta es una nota al pie
```

```markdown
También se puede agregar directamente en el texto^[De esta forma].
```





## Configuración básica

Header
- yaml


### Títulos

```yaml
title: "Probando"
author: "Bastián Olea Herrera"
date: 2025-04-01
lang: es
```

```yaml
lang: es
language: 
  title-block-author-single: "Creado por"
```

```yaml
title-block-banner: "#f0f3f5"
title-block-banner-color: "black"
```




### Autocontenido
Para que el documento no tenga dependencias externas, sino que sea portable
```yaml
format:
  html:
    embed-resources: true
```




### Índices o tablas de contenido
https://quarto.org/docs/output-formats/html-basics.html#table-of-contents

```yaml
format:
  html
    toc: true
    number-sections: true
    toc-expand: 2
```


Poner enlaces debajo del índice
```yaml
format:
  html:
    other-links:
      - text: Enlace 1
        href: https://data.nasa.gov/
      - text: Enlace 2
        href: https://data.nasa.gov/
```








### Temas
https://quarto.org/docs/output-formats/html-themes.html

```yaml
mainfont: Courier
theme: pulse
theme: darkly
fontsize: "20px"
```


----


## Disposición
https://quarto.org/docs/output-formats/html-basics.html


### Pestañas
https://quarto.org/docs/output-formats/html-basics.html#tabsets
```markdown
::: {.panel-tabset .nav-pills}

## Scatterplot
Content that will show under first tab

## Boxplot
Content that will show under first tab

## Barplot
Content that will show under first tab
:::
```

También puede ser solo `::: {.panel-tabset}`





### Columnas
```markdown
:::: {.columns}
::: {.column width="40%"} 
Columna izquierda
:::

::: {.column width="60%"}
Columna derecha
:::
```

Otra forma:
```markdown
:::: {.grid}

::: {.g-col-3}
First column 
I would like to have text here
Sentence becomes longer, it should automatically stay in their column
:::
  
::: {.g-col-9}
Second column 
and here
More text
:::
  
:::: 
```







----


## Chunks


Configuración de Chunks
- echo: false
- mensajes, errores y alertas
- eval: false
- tamaño de figuras
- output: asis

Configuración de Quarto
- índice
- tamaño de figuras
- tipografías
- temas
- self-contained


### Código entre el texto
```markdown
`r iris$Species[1]`
```


----



## Avanzado
### css

```yaml
css: style.scss
```

```scss
/*-- scss:defaults --*/
$h2-font-size:          1.6rem !default;
$headings-font-weight:  500 !default;
$toc-color: #127679;

/*-- scss:rules --*/
h1, h2, h3, h4, h5, h6 {
  text-shadow: -1px -1px 0 rgba(0, 0, 0, .3);
}
```

```css
h1, .h1, h2, .h2, h3, .h3 {
    margin-top: 84px;
}

h2 {
font-size: 140%;
margin-top: 24px;
}
```



### Viñetas debajo de figuras
```r
#| fig.cap = "Figure: Here is a really important caption."
```


### Enlaces internos

```markdown
# Data wrangling {#section-2}
```

```markdown
Here is the link to the [section 2](#section-2) of the document!
```

### Ocultar código

```yaml
format:
  html:
    code-fold: true
    code-summary: "Show the code"
```


Contenido en los márgenes

```markdown
::: {.column-margin}
Hi! I'm a side note!
:::
```

```markdown
::: {.aside}
\
This is an example. This is an example. This is an example. This is an example. This is an example. This is an example. This is an example. This is an example. This is an example. This is an example. This is an example. This is an example. 
:::
```


````markdown
```{r}
#| column: margin

knitr::kable(
  mtcars[1:3, 1:3]
)
```
````


### HTML
```html
<div style = "background: red;">
polli
</div>
```


### Bloques


## Bloques
````markdown
::: {style="max-height: 400px; overflow-y: scroll;"}
contenido largo
:::
````



### Condicionalidad

```markdown
::: {.content-visible when-format="html"}
```









----

## Reportes parametrizados


https://posit.co/blog/parameterized-quarto/
https://rfortherestofus.com/2024/06/parameterized-reporting-quarto

Render one report using the quarto R package:

```r
library(quarto)
quarto_render(
  input = "example.qmd",
  execute_params = list(
    continent = "Europe"
  )
)
```

Use the purrr package to create multiple reports at the same time:

```r
library(purrr)
walk(
  .x = unique(gapminder$continent),
  .f = ~quarto_render(
    input = "example.qmd",
    execute_params = list(
      choose_continent = .x
    )
  )
)
```

Why is there only one report? We need to give each report a different name, to stop it being overwritten. Let’s use glue() again, this time for the file names.

```r
walk(
  .x = unique(gapminder$continent),
  .f = ~quarto_render(
    input = "example.qmd",
    output_file = glue("report_{.x}.html"),
    execute_params = list(
      choose_continent = .x
    )
  )
)
```

To ensure the images aren’t overwritten as well, you may need to add embed-resources: true to your Quarto document YAML:

```r
---
format:
  html:
    embed-resources: true
---
```

This keeps any plots created embedded within the HTML document, instead of in a separate folder.